language: erlang
otp_release:
  - 20.0
  - 21.0
notifications:
  email:
    - maxim@synrc.com
script:
  - "curl -fsSL https://raw.github.com/synrc/mad/master/mad > mad"
  - "chmod +x mad"
  - "./mad dep com"
